kind = "web"
previewPath = "/"
title = "Studio Inova"
version = "1.0.0"
id = "artifacts/studio-inova"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19589

[services.development]
run = "pnpm --filter @workspace/studio-inova run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/studio-inova", "run", "build" ]
publicDir = "artifacts/studio-inova/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19589"
BASE_PATH = "/"
